version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx_set.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

  django:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/code
    expose:
      - "8000"
