# Generated by Django 4.1.7 on 2023-02-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(default='')),
                ('seq_num', models.TextField(blank=True, default='')),
            ],
        ),
    ]
